Sensores().reportarEvento("Fiesta1", 9)
Sensores().reportarEvento("Fiesta2", 11)
Sensores().reportarEvento("Fiesta3", 9)
Sensores().reportarEvento("Fiesta4", 18)
Sensores().reportarEvento("Fiesta5", 3)
Sensores().reportarEvento("Fiesta6", 23)
Sensores().reportarEvento("Fiesta7", 6)
Sensores().reportarEvento("Fiesta8", 16)
Sensores().reportarEvento("Fiesta9", 12)
Sensores().reportarEvento("Fiesta10", 1)
Sensores().reportarEvento("Fiesta11", 32)

Evento("Concierto", "1", "1").indCalor()
Evento("Fiesta", "1", "2").indCalor()
Evento("Plaza", "3", "3").indCalor()
Evento("Prueba", "1", "1").indCalor()
Evento("Accidente_moto", "1", "1").indCalor()
Evento("Accidente_auto", "3", "4").indCalor()
Evento("Fiesta", "9", "6").indCalor()
Evento("Fiesta2", "9", "1").indCalor()
Evento("Fiesta3", "3", "9").indCalor()
Evento("Fiesta4", "4", "2").indCalor()
Evento("Fiesta4", "4", "2").indCalor()
Evento("Fiesta4", "4", "2").indCalor()
Evento("Fiesta4", "4", "2").indCalor()
Evento("Fiesta4", "4", "2").indCalor()
Evento("Fiesta4", "4", "2").indCalor()
Evento("Fiesta4", "4", "2").indCalor()
Evento("Fiesta4", "4", "2").indCalor()

Sensores().crearEvento("Fiesta1", "9", "6")
Sensores().crearEvento("Fiesta2", "9", "1")
Sensores().crearEvento("Fiesta3", "3", "9")
Sensores().crearEvento("Fiesta4", "4", "2")
Sensores().crearEvento("Fiesta5", "6", "7")
Sensores().crearEvento("Fiesta6", "2", "8")
Sensores().crearEvento("Fiesta7", "6", "3")
Sensores().crearEvento("Fiesta8", "1", "6")
Sensores().crearEvento("Fiesta9", "4", "1")
Sensores().crearEvento("Fiesta10", "5", "8")
Sensores().crearEvento("Fiesta11", "5", "6")
